import Footer from "@/component/footer/page";
import Header from "@/component/header/page";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hotelnine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/static/css/timepicker.css" />
        <link rel="stylesheet" href="/static/datepicker/jquery-ui.min.css" />
        <link
          rel="stylesheet"
          href="/static/datepicker/jquery-ui.structure.min.css"
        />
        <link
          rel="stylesheet"
          href="/static/datepicker/jquery-ui.theme.min.css"
        />
        <link rel="stylesheet" href="/static/css/reset.css" />
        <link rel="stylesheet" href="/static/css/gallery_styles.css" />
        <link rel="stylesheet" href="/static/css/styles.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-embedded.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7.css" />
        <link rel="stylesheet" href="/static/gerege/gerege.css" />
        <link rel="stylesheet" href="/static/css/animate.css" />
        <link
          rel="stylesheet"
          href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="/static/font-awesome-4.7.0/css/font-awesome.min.css"
        />
        <link rel="stylesheet" href="/static/swiper/css/swiper.min.css" />
        <link rel="stylesheet" href="/static/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="/static/css/main.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        {/* <script src="jquery-3.7.1.min.js" async /> */}
        <script
          src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"
          async
        />

        <script src="static/js/scripts.js" async />
        <script src="static/bootstrap-3.3.7-dist/js/bootstrap.min.js" async />
        <script src="static/js/jquery.simpleWeather.min.js" async />
        <script src="static/js/owl.carousel.min.js" async />
        <script src="static/datepicker/jquery-ui.min.js" async />

        <script
          src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
          async
          integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
